#!/usr/bin/env bash

set -euo pipefail

# options
HAS_ACTION=false
RUN_BUILD=false
RUN_UPDATE=false
RUN_DESTROY=false

NAME=caasp-stack
OPENRC_FILE=
HEAT_ENVIRONMENT_FILE=heat-environment.yaml
HEAT_TEMPLATE_FILE=
MASTERS=3
WORKERS=2
IMAGE=


USAGE=$(cat <<USAGE
Usage:

  * Building a cluster

    -b|--build                       Run the Heat Stack Build Step
    -m|--masters             <INT>   Number of masters to build (Default: 3)
    -w|--workers             <INT>   Number of workers to build (Default: 2)
    -i|--image               <STR>   Image to use

  * Destroying a cluster

    -d|--destroy                     Run the Heat Stack Destroy Step

  * Common options

    -o|--openrc             <STR>   Path to an openrc file
    -e|--heat-environment   <STR>   Path to a heat environment file
    -t|--heat-template      <STR>   Path to the heat template to use

  * Examples:

  Build a 1 master, 2 worker cluster

  $0 --build -m 1 -w 2 --openrc my-openrc --image CaaSP-1.0.0-GM --name test-stack

  Build a 3 master, 2 worker cluster

  $0 --build -m 3 -w 2 --openrc my-openrc --image CaaSP-1.0.0-GM --name test-stack

USAGE
)

# Utility methods
log()        { (>&2 echo ">>> [caasp-stack] $@") ; }
warn()       { log "WARNING: $@" ; }
error()      { log "ERROR: $@" ; exit 1 ; }
check_file() { if [ ! -f $1 ]; then error "File $1 doesn't exist!"; fi }

# parse options
while [[ $# -gt 0 ]] ; do
  case $1 in
    -n|--name)
      # Convert name to lower cases, as cloud-init will do with the machines
      # hostname.
      NAME="${2,,}"
      shift
      ;;
    -o|--openrc)
      f="$(realpath $2)"
      check_file "$f"
      OPENRC_FILE="$f"
      shift
      ;;
    -e|--heat-environment)
      f="$(realpath $2)"
      check_file "$f"
      HEAT_ENVIRONMENT_FILE="$f"
      shift
      ;;
    -t|--heat-template)
      f="$(realpath $2)"
      check_file "$f"
      HEAT_TEMPLATE_FILE="$f"
      shift
      ;;
    -b|--build)
      RUN_BUILD=true
      HAS_ACTION=true
      ;;
    -m|--masters)
      MASTERS="$2"
      shift
      ;;
    -w|--workers)
      WORKERS="$2"
      shift
      ;;
    -i|--image)
      IMAGE="$2"
      shift
      ;;
    -u|--update)
      RUN_UPDATE=true
      HAS_ACTION=true
      ;;
    -d|--destroy)
      RUN_DESTROY=true
      HAS_ACTION=true
      ;;
    -h|--help)
      echo "$USAGE"
      exit 0
      ;;
    *)
      log "Invalid option: $1"
      usage
      ;;
  esac
  shift
done

[ -z "$OPENRC_FILE" ]  && error "Option --openrc is required"

# Core methods
update_load_balancer_security_groups() {
    local vip_port_id=$(openstack stack resource show "$NAME" master_lb -f json | jq -r '.attributes.vip_port_id')
    local resource_list=$(openstack stack resource list "$NAME" -f json)
    local secgroup_base_id=$(echo "$resource_list" | jq -r '.[] | select( .resource_name == "secgroup_base" ) | "\(.physical_resource_id)"')
    local secgroup_master_id=$(echo "$resource_list" | jq -r '.[] | select( .resource_name == "secgroup_master" ) | "\(.physical_resource_id)"')

    log "Adding the load balancer vip port $vip_port_id security groups to:"
    log "  secgroup_base: $secgroup_base_id"
    log "  secgroup_master: $secgroup_master_id"

    openstack port set --security-group "$secgroup_base_id" --security-group "$secgroup_master_id" "$vip_port_id"
}

build_stack() {
  [ -z "$NAME" ] && error "Option --name is required"
  [ -z "$HEAT_TEMPLATE_FILE" ]  && error "Option --heat-template is required"

  source "$OPENRC_FILE"

  if [ -z "$IMAGE" ]; then
    # If image not given get latest devel image
    IMAGE=$(openstack image list --format json --property caasp-channel='devel' --sort caasp-version:desc | jq -r '.[0].Name')

    [ -z "$IMAGE" ] && error "Could not find the latest image try using the --image option"
  fi

  log "Creating Stack with image $IMAGE"

  # Keep track of the stack name (which Heat enforces as being unique) for
  # later use in commands like delete.
  echo -n "$NAME" > .stack_name

  if [ ${MASTERS} -gt 1 ]; then
    openstack stack create --wait -e "$HEAT_ENVIRONMENT_FILE" -t "$HEAT_TEMPLATE_FILE" "$NAME" \
    --parameter master_count=$MASTERS \
    --parameter worker_count=$WORKERS \
    --parameter image="$IMAGE"

    # Assume load balancer with more than one master
    update_load_balancer_security_groups
  else
    openstack stack create --wait -e "$HEAT_ENVIRONMENT_FILE" -t "$HEAT_TEMPLATE_FILE" "$NAME" \
    --parameter worker_count=$WORKERS \
    --parameter image="$IMAGE"
  fi

  log "CaaSP Stack Created with name $NAME"

  ./tools/generate-environment "$NAME"
  ../misc-tools/generate-ssh-config environment.json

  log "Waiting for Velum to start - this may take a while"
  PYTHONUNBUFFERED=1 "../misc-tools/wait-for-velum" https://$(jq -r '.dashboardExternalHost' environment.json)
}

update_stack() {
  [ -z "$IMAGE" ] && error "Option --image is required"
  [ -z "$HEAT_TEMPLATE_FILE" ]  && error "Option --heat-template is required"

  local stack_name=$(cat .stack_name)
  [ -n "$NAME" ] && stack_name="$NAME"

  log "Updating Stack with ID $stack_name"

  source "$OPENRC_FILE"

  if [ ${MASTERS} -gt 1 ]; then
      openstack stack update --wait -e "$HEAT_ENVIRONMENT_FILE" -t "$HEAT_TEMPLATE_FILE" "$stack_name" \
        --parameter master_count=$MASTERS \
        --parameter worker_count=$WORKERS \
        --parameter image="$IMAGE"
  else
      openstack stack update --wait -e "$HEAT_ENVIRONMENT_FILE" -t "$HEAT_TEMPLATE_FILE" "$stack_name" \
        --parameter worker_count=$WORKERS \
        --parameter image="$IMAGE"
  fi

  ./tools/generate-environment "$NAME"
  ../misc-tools/generate-ssh-config environment.json
}

destroy_stack() {
  local stack_name="$(cat .stack_name)"
  [ -n "$NAME" ] && stack_name="$NAME"

  log "Deleting Stack with name $stack_name"

  source "$OPENRC_FILE"
  openstack stack delete --yes --wait "$stack_name"
  rm -f .stack_name
}

# main
if [ "$HAS_ACTION" != true ]; then
  echo "$USAGE"
  error "No action arguments were supplied"
fi

if [ "$RUN_BUILD" = true ]; then
  build_stack
fi

if [ "$RUN_UPDATE" = true ]; then
  update_stack
fi

if [ "$RUN_DESTROY" = true ] ; then
  destroy_stack
fi

log "Done"
