#!/usr/bin/env bash

set -euo pipefail

chmod 600 ../misc-files/id_shared

DIR="$( cd "$( dirname "$0" )" && pwd )"
STACK_NAME=${1:?A stack name must be provided}

${DIR}/get_node_info.py ${STACK_NAME}
cat environment.json
