version: '3'
# note: this expects the open-ldap server to already be docker-compose up'd

services:

  testbox:
    build: .
    container_name: testbox
    #image: opensuse/leap:15.0
    command: sleep infinity
    networks:
     #- openldap-test
     - open-ldap-server_openldap-test

networks:
  open-ldap-server_openldap-test:
    external: true
